logging:
  subscribers:
    - format: pretty
      level: TRACE
      targets:
        h2: INFO
        hyper: INFO
        rdkafka: INFO
        tonic: INFO
        tower: INFO
      color: true
      print:
        target: true
    - format: compact
      level: DEBUG
      output:
        type: file
        path: advanced_server.log
    - format: json
      level: DEBUG
      output:
        type: file
        path: advanced_server.json.log
      flatten_metadata: true
      current_span: true
      static_fields:
        env: dev
        something: something
        other: 42
    - format: json
      level: DEBUG
      output:
        type: kafka
        topic: logtest
        brokers:
          - localhost:9092
      flatten_metadata: true
      current_span: false
      print:
        target: true
        file: true
        line_number: true
      static_fields:
        env: dev
        something: something
        other: 42
handlers:
  hello_world:
    disabled: false
    rate_limit:
      rps: 1
  call_inner:
    cors:
      origins: any
      max_age: 60s
telemetry:
  labels:
    env: example
tracing:
  exporters:
    - type: otlp
      endpoint: http://localhost:4317
  include:
    location: true
    exception_from_error_fields: true
    exception_from_error_events: true
    status_from_error_events: true
    inactivity: true
    thread_info: true
  level: TRACE
  # Whether to include HTTP headers in tracing spans and logs. Can be helpful
  # if sensitive data is present in headers (i.e. authentication data).
  include_headers: false
  # Level at which request start log is emitted
  request_level: DEBUG
  # Level at which request finish log is emitted
  response_level: INFO
http_clients:
  tracing:
    connect_timeout: 100ms
    timeout: 200ms
    verbose: true
    cb:
      error_rate: 0.3
      closed_len: 10
      half_open_len: 3
      open_wait: 10s
auth:
  extractor:
    type: stacked
    extractors:
      - type: jwt
        realm: UXUM_REALM
        algo: HS256
        key:
          raw_hmac_secret: hunter2
        validate:
          required_claims:
            - exp
            - aud
            - sub
          leeway: 2m
          validate_exp: true
          validate_aud: true
          audience:
            - API_ID_01
      - type: basic
        realm: UXUM_REALM
      - type: header
        user_header: x-username
        token_header: x-password
  provider:
    type: config
  users:
    test:
      password: test
      roles:
        - role1
        - role2
    guest:
      password: guest
    super:
      password: super
      roles:
        - super
  roles:
    super:
      super_user: true
    role1:
      permissions:
        - perm1
        - perm2
    role2:
      permissions:
        - perm3
        - perm4
        - maintenance
server:
  listen: 127.0.0.1:8080
  tls:
    listen: 127.0.0.1:8443
    cert: examples/advanced_server/tls.crt
    key: examples/advanced_server/tls.key
